### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by leonou2010** [emnlp2020qdgat/QDGAT#3]
when running the run.sh, the below error occurs

Namespace(batch_size=16, bert_learning_rate=1.5e-05, bert_weight_decay=0.01, data_dir='data', do_eval=True, do_train=True, dropout=0.1, eps=1e-06, eval_batch_size=5, grad_clipping=1.0, gradient_accumulation_steps=8, learning_rate=0.0001, log_per_updates=100, max_epoch=5, optimizer='adam', passage_length_limit=463, pre_path=None, question_length_limit=46, roberta_model='roberta-base', save_dir='output', seed=1117, warmup=0.06, warmup_schedule='warmup_linear', weight_decay=5e-05)
Downloading: 100%|█████████████████████████████████████████████████████████████████████████| 899k/899k [00:01<00:00, 774kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████| 456k/456k [00:01<00:00, 397kB/s]
Load data from train.pkl.
Load data size 3193.
Load data from dev.pkl.
Load data size 3376.
Traceback (most recent call last):
  File "main.py", line 279, in <module>
    main()
  File "main.py", line 274, in main
    train(args, network, train_dataset, eval_dataset)
  File "main.py", line 142, in train
    output_dict = network(**batch)
  File "/root/miniconda3/envs/qdgat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/scott/QDGAT-master/qdgat/network.py", line 145, in forward
    sequence_output_list = [ item for item in outputs[2][-4:] ]
  File "/root/miniconda3/envs/qdgat/lib/python3.7/site-packages/transformers/file_utils.py", line 1360, in __getitem__
    return self.to_tuple()[k]
IndexError: tuple index out of range

**Comment by chadlzx** [comment]
Please attention to the version of Transformers. You should add parameters **output_hidden_states=True** to the self.bert(...)
